
# This file is automatically generated, you probably don't want to edit this

dcompOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dcompOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            dataDone = FALSE,
            minScale = "autoMin",
            userMinScale = 0,
            maxScale = "autoMax",
            userMaxScale = 0,
            win = 7,
            Order = "data", ...) {

            super$initialize(
                package="casnetjmv",
                name="dcomp",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..dataDone <- jmvcore::OptionBool$new(
                "dataDone",
                dataDone,
                default=FALSE)
            private$..minScale <- jmvcore::OptionList$new(
                "minScale",
                minScale,
                options=list(
                    "autoMin",
                    "userMin"),
                default="autoMin")
            private$..userMinScale <- jmvcore::OptionNumber$new(
                "userMinScale",
                userMinScale,
                default=0)
            private$..maxScale <- jmvcore::OptionList$new(
                "maxScale",
                maxScale,
                options=list(
                    "autoMax",
                    "userMax"),
                default="autoMax")
            private$..userMaxScale <- jmvcore::OptionNumber$new(
                "userMaxScale",
                userMaxScale,
                default=0)
            private$..win <- jmvcore::OptionNumber$new(
                "win",
                win,
                default=7)
            private$..Order <- jmvcore::OptionList$new(
                "Order",
                Order,
                options=list(
                    "data",
                    "alpha",
                    "means"),
                default="data")

            self$.addOption(private$..deps)
            self$.addOption(private$..dataDone)
            self$.addOption(private$..minScale)
            self$.addOption(private$..userMinScale)
            self$.addOption(private$..maxScale)
            self$.addOption(private$..userMaxScale)
            self$.addOption(private$..win)
            self$.addOption(private$..Order)
        }),
    active = list(
        deps = function() private$..deps$value,
        dataDone = function() private$..dataDone$value,
        minScale = function() private$..minScale$value,
        userMinScale = function() private$..userMinScale$value,
        maxScale = function() private$..maxScale$value,
        userMaxScale = function() private$..userMaxScale$value,
        win = function() private$..win$value,
        Order = function() private$..Order$value),
    private = list(
        ..deps = NA,
        ..dataDone = NA,
        ..minScale = NA,
        ..userMinScale = NA,
        ..maxScale = NA,
        ..userMaxScale = NA,
        ..win = NA,
        ..Order = NA)
)

dcompResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dcompResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        tsplot = function() private$.items[["tsplot"]],
        CRplot = function() private$.items[["CRplot"]],
        CCPplot = function() private$.items[["CCPplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dynamic Complexity")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Dynamic Complexity"))
            self$add(jmvcore::Image$new(
                options=options,
                name="tsplot",
                title="(Multivariate) Time series",
                width=700,
                height=300,
                renderFun=".tsplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="CRplot",
                title="Complexity Resonance Diagram",
                width=700,
                height=400,
                renderFun=".CRplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="CCPplot",
                title="Cumulative Complexity Peaks",
                width=700,
                height=400,
                renderFun=".CCPplot"))}))

dcompBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dcompBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "casnetjmv",
                name = "dcomp",
                version = c(1,0,0),
                options = options,
                results = dcompResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Dynamic Complexity
#'
#' 
#' @param data .
#' @param deps .
#' @param dataDone .
#' @param minScale .
#' @param userMinScale .
#' @param maxScale .
#' @param userMaxScale .
#' @param win .
#' @param Order .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tsplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$CRplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$CCPplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
dcomp <- function(
    data,
    deps,
    dataDone = FALSE,
    minScale = "autoMin",
    userMinScale = 0,
    maxScale = "autoMax",
    userMaxScale = 0,
    win = 7,
    Order = "data") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dcomp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL))


    options <- dcompOptions$new(
        deps = deps,
        dataDone = dataDone,
        minScale = minScale,
        userMinScale = userMinScale,
        maxScale = maxScale,
        userMaxScale = userMaxScale,
        win = win,
        Order = Order)

    analysis <- dcompClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

