
# This file is automatically generated, you probably don't want to edit this

faSDAOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "faSDAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            y1 = NULL,
            standardise = "meanSD",
            sumORDER = FALSE,
            removeTrend = "nodet",
            polydet_order = 1,
            scaleExclude = 4, ...) {

            super$initialize(
                package='casnetjmv',
                name='faSDA',
                requiresData=TRUE,
                ...)

            private$..y1 <- jmvcore::OptionVariable$new(
                "y1",
                y1)
            private$..standardise <- jmvcore::OptionList$new(
                "standardise",
                standardise,
                options=list(
                    "meanSD",
                    "medianMAD"),
                default="meanSD")
            private$..sumORDER <- jmvcore::OptionBool$new(
                "sumORDER",
                sumORDER,
                default=FALSE)
            private$..removeTrend <- jmvcore::OptionList$new(
                "removeTrend",
                removeTrend,
                options=list(
                    "nodet",
                    "polydet"),
                default="nodet")
            private$..polydet_order <- jmvcore::OptionInteger$new(
                "polydet_order",
                polydet_order,
                default=1)
            private$..scaleExclude <- jmvcore::OptionNumber$new(
                "scaleExclude",
                scaleExclude,
                default=4)

            self$.addOption(private$..y1)
            self$.addOption(private$..standardise)
            self$.addOption(private$..sumORDER)
            self$.addOption(private$..removeTrend)
            self$.addOption(private$..polydet_order)
            self$.addOption(private$..scaleExclude)
        }),
    active = list(
        y1 = function() private$..y1$value,
        standardise = function() private$..standardise$value,
        sumORDER = function() private$..sumORDER$value,
        removeTrend = function() private$..removeTrend$value,
        polydet_order = function() private$..polydet_order$value,
        scaleExclude = function() private$..scaleExclude$value),
    private = list(
        ..y1 = NA,
        ..standardise = NA,
        ..sumORDER = NA,
        ..removeTrend = NA,
        ..polydet_order = NA,
        ..scaleExclude = NA)
)

faSDAResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        tblTS = function() private$.items[["tblTS"]],
        tblSDA = function() private$.items[["tblSDA"]],
        tsplot = function() private$.items[["tsplot"]],
        sdaplot = function() private$.items[["sdaplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Standardised Dispersion Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="tblTS",
                title="Time series descriptives",
                rows=2,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="integer", 
                        `title`="valid N"),
                    list(
                        `name`="na", 
                        `type`="integer", 
                        `title`="NA values"),
                    list(
                        `name`="median", 
                        `type`="number"),
                    list(
                        `name`="mad", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `type`="number"),
                    list(
                        `name`="standardise", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tblSDA",
                title="DFA parameters and results",
                rows=2,
                columns=list(
                    list(
                        `name`="method", 
                        `title`="regression method", 
                        `type`="text"),
                    list(
                        `name`="Hadjust", 
                        `title`="adjust H", 
                        `type`="number"),
                    list(
                        `name`="detrending", 
                        `title`="detrend method", 
                        `type`="text"),
                    list(
                        `name`="minScale", 
                        `title`="min. scale", 
                        `type`="number"),
                    list(
                        `name`="maxScale", 
                        `title`="max. scale", 
                        `type`="number"),
                    list(
                        `name`="slope", 
                        `title`="log-log slope", 
                        `type`="number"),
                    list(
                        `name`="H", 
                        `type`="number"),
                    list(
                        `name`="FD", 
                        `title`="informed FD", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="tsplot",
                title="Time series",
                width=700,
                height=300,
                renderFun=".tsplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="sdaplot",
                title="log-log regression",
                width=700,
                height=400,
                renderFun=".sdaplot"))}))

faSDABase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "faSDABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'casnetjmv',
                name = 'faSDA',
                version = c(1,0,0),
                options = options,
                results = faSDAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Standardised Dispersion Analysis
#'
#' 
#' @param data .
#' @param y1 .
#' @param standardise .
#' @param sumORDER .
#' @param removeTrend .
#' @param polydet_order .
#' @param scaleExclude .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tblTS} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tblSDA} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tsplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$sdaplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tblTS$asDF}
#'
#' \code{as.data.frame(results$tblTS)}
#'
#' @export
faSDA <- function(
    data,
    y1,
    standardise = "meanSD",
    sumORDER = FALSE,
    removeTrend = "nodet",
    polydet_order = 1,
    scaleExclude = 4) {

    if ( ! requireNamespace('jmvcore'))
        stop('faSDA requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(y1), y1, NULL))

    options <- faSDAOptions$new(
        y1 = y1,
        standardise = standardise,
        sumORDER = sumORDER,
        removeTrend = removeTrend,
        polydet_order = polydet_order,
        scaleExclude = scaleExclude)

    results <- faSDAResults$new(
        options = options)

    analysis <- faSDAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
