
# This file is automatically generated, you probably don't want to edit this

recNetOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "recNetOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            y1 = NULL,
            standardise = "none",
            emLag = 1,
            emDim = 1,
            Gweight = NULL,
            Gdirect = NULL,
            Glabels = NULL,
            Glayout = NULL,
            PruneDegree = 0,
            PruneWeight = 0,
            nsize = "degree",
            fixRR = 0.05,
            fixRAD = 0,
            fixed = "RAD",
            DLmin = 2,
            DLmax = 0,
            VLmin = 2,
            VLmax = 0,
            HLmin = 2,
            HLmax = 0,
            theiler = 0,
            norm = "euclidean", ...) {

            super$initialize(
                package='casnetjmv',
                name='recNet',
                requiresData=TRUE,
                ...)

            private$..y1 <- jmvcore::OptionVariable$new(
                "y1",
                y1)
            private$..standardise <- jmvcore::OptionList$new(
                "standardise",
                standardise,
                options=list(
                    "none",
                    "meanSD",
                    "medianMAD",
                    "unitScale",
                    "symbolicScale"),
                default="none")
            private$..emLag <- jmvcore::OptionNumber$new(
                "emLag",
                emLag,
                default=1)
            private$..emDim <- jmvcore::OptionNumber$new(
                "emDim",
                emDim,
                default=1)
            private$..Gweight <- jmvcore::OptionBool$new(
                "Gweight",
                Gweight)
            private$..Gdirect <- jmvcore::OptionBool$new(
                "Gdirect",
                Gdirect)
            private$..Glabels <- jmvcore::OptionBool$new(
                "Glabels",
                Glabels)
            private$..Glayout <- jmvcore::OptionList$new(
                "Glayout",
                Glayout,
                options=list(
                    "ci",
                    "st",
                    "ni",
                    "tr",
                    "fr",
                    "md",
                    "cl"))
            private$..PruneDegree <- jmvcore::OptionNumber$new(
                "PruneDegree",
                PruneDegree,
                default=0)
            private$..PruneWeight <- jmvcore::OptionNumber$new(
                "PruneWeight",
                PruneWeight,
                default=0)
            private$..nsize <- jmvcore::OptionList$new(
                "nsize",
                nsize,
                default="degree",
                options=list(
                    "degree",
                    "hubscore",
                    "fixed"))
            private$..fixRR <- jmvcore::OptionNumber$new(
                "fixRR",
                fixRR,
                default=0.05)
            private$..fixRAD <- jmvcore::OptionNumber$new(
                "fixRAD",
                fixRAD,
                default=0)
            private$..fixed <- jmvcore::OptionList$new(
                "fixed",
                fixed,
                default="RAD",
                options=list(
                    "RR",
                    "RR",
                    "NO"))
            private$..DLmin <- jmvcore::OptionNumber$new(
                "DLmin",
                DLmin,
                default=2)
            private$..DLmax <- jmvcore::OptionNumber$new(
                "DLmax",
                DLmax,
                default=0)
            private$..VLmin <- jmvcore::OptionNumber$new(
                "VLmin",
                VLmin,
                default=2)
            private$..VLmax <- jmvcore::OptionNumber$new(
                "VLmax",
                VLmax,
                default=0)
            private$..HLmin <- jmvcore::OptionNumber$new(
                "HLmin",
                HLmin,
                default=2)
            private$..HLmax <- jmvcore::OptionNumber$new(
                "HLmax",
                HLmax,
                default=0)
            private$..theiler <- jmvcore::OptionNumber$new(
                "theiler",
                theiler,
                default=0)
            private$..norm <- jmvcore::OptionList$new(
                "norm",
                norm,
                options=list(
                    "euclidean",
                    "maximum",
                    "manhattan",
                    "canberra",
                    "binary",
                    "minkowski"),
                default="euclidean")

            self$.addOption(private$..y1)
            self$.addOption(private$..standardise)
            self$.addOption(private$..emLag)
            self$.addOption(private$..emDim)
            self$.addOption(private$..Gweight)
            self$.addOption(private$..Gdirect)
            self$.addOption(private$..Glabels)
            self$.addOption(private$..Glayout)
            self$.addOption(private$..PruneDegree)
            self$.addOption(private$..PruneWeight)
            self$.addOption(private$..nsize)
            self$.addOption(private$..fixRR)
            self$.addOption(private$..fixRAD)
            self$.addOption(private$..fixed)
            self$.addOption(private$..DLmin)
            self$.addOption(private$..DLmax)
            self$.addOption(private$..VLmin)
            self$.addOption(private$..VLmax)
            self$.addOption(private$..HLmin)
            self$.addOption(private$..HLmax)
            self$.addOption(private$..theiler)
            self$.addOption(private$..norm)
        }),
    active = list(
        y1 = function() private$..y1$value,
        standardise = function() private$..standardise$value,
        emLag = function() private$..emLag$value,
        emDim = function() private$..emDim$value,
        Gweight = function() private$..Gweight$value,
        Gdirect = function() private$..Gdirect$value,
        Glabels = function() private$..Glabels$value,
        Glayout = function() private$..Glayout$value,
        PruneDegree = function() private$..PruneDegree$value,
        PruneWeight = function() private$..PruneWeight$value,
        nsize = function() private$..nsize$value,
        fixRR = function() private$..fixRR$value,
        fixRAD = function() private$..fixRAD$value,
        fixed = function() private$..fixed$value,
        DLmin = function() private$..DLmin$value,
        DLmax = function() private$..DLmax$value,
        VLmin = function() private$..VLmin$value,
        VLmax = function() private$..VLmax$value,
        HLmin = function() private$..HLmin$value,
        HLmax = function() private$..HLmax$value,
        theiler = function() private$..theiler$value,
        norm = function() private$..norm$value),
    private = list(
        ..y1 = NA,
        ..standardise = NA,
        ..emLag = NA,
        ..emDim = NA,
        ..Gweight = NA,
        ..Gdirect = NA,
        ..Glabels = NA,
        ..Glayout = NA,
        ..PruneDegree = NA,
        ..PruneWeight = NA,
        ..nsize = NA,
        ..fixRR = NA,
        ..fixRAD = NA,
        ..fixed = NA,
        ..DLmin = NA,
        ..DLmax = NA,
        ..VLmin = NA,
        ..VLmax = NA,
        ..HLmin = NA,
        ..HLmax = NA,
        ..theiler = NA,
        ..norm = NA)
)

recNetResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        tblTS = function() private$.items[["tblTS"]],
        rpplot = function() private$.items[["rpplot"]],
        rnetplot = function() private$.items[["rnetplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Recurrence Networks")
            self$add(jmvcore::Table$new(
                options=options,
                name="tblTS",
                title="Time series descriptives",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="vlevel", 
                        `title`="type", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="integer", 
                        `title`="valid N"),
                    list(
                        `name`="na", 
                        `type`="integer", 
                        `title`="NA values"),
                    list(
                        `name`="transformed", 
                        `title`="transformation", 
                        `type`="text"),
                    list(
                        `name`="uni_obs", 
                        `title`="# of unique values", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="rpplot",
                title="Recurrence Plot",
                width=600,
                height=600,
                renderFun=".rpplot",
                clearWith=list(
                    "y1",
                    "emRad",
                    "emLag",
                    "emDim",
                    "VLmin",
                    "DLmin",
                    "HLmin",
                    "VLmax",
                    "DLmax",
                    "HLmax",
                    "fixRR",
                    "fixRAD",
                    "fixed",
                    "theiler",
                    "norm",
                    "standardise",
                    "Gweight")))
            self$add(jmvcore::Image$new(
                options=options,
                name="rnetplot",
                title="Recurrence Network",
                width=600,
                height=600,
                visible=TRUE,
                renderFun=".rnetplot",
                clearWith=list(
                    "y1",
                    "emRad",
                    "emLag",
                    "emDim",
                    "VLmin",
                    "DLmin",
                    "HLmin",
                    "VLmax",
                    "DLmax",
                    "HLmax",
                    "fixRR",
                    "fixRAD",
                    "fixed",
                    "theiler",
                    "norm",
                    "Gdirect",
                    "Gweight",
                    "Glayout",
                    "standardise",
                    "nsize",
                    "Glabels",
                    "PruneDegree",
                    "PruneWeight")))}))

recNetBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "recNetBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'casnetjmv',
                name = 'recNet',
                version = c(1,0,0),
                options = options,
                results = recNetResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Recurrence Networks
#'
#' 
#' @param data .
#' @param y1 .
#' @param standardise .
#' @param emLag .
#' @param emDim .
#' @param Gweight .
#' @param Gdirect .
#' @param Glabels .
#' @param Glayout .
#' @param PruneDegree .
#' @param PruneWeight .
#' @param nsize .
#' @param fixRR .
#' @param fixRAD .
#' @param fixed .
#' @param DLmin .
#' @param DLmax .
#' @param VLmin .
#' @param VLmax .
#' @param HLmin .
#' @param HLmax .
#' @param theiler .
#' @param norm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tblTS} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rpplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$rnetplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tblTS$asDF}
#'
#' \code{as.data.frame(results$tblTS)}
#'
#' @export
recNet <- function(
    data,
    y1,
    standardise = "none",
    emLag = 1,
    emDim = 1,
    Gweight,
    Gdirect,
    Glabels,
    Glayout,
    PruneDegree = 0,
    PruneWeight = 0,
    nsize = "degree",
    fixRR = 0.05,
    fixRAD = 0,
    fixed = "RAD",
    DLmin = 2,
    DLmax = 0,
    VLmin = 2,
    VLmax = 0,
    HLmin = 2,
    HLmax = 0,
    theiler = 0,
    norm = "euclidean") {

    if ( ! requireNamespace('jmvcore'))
        stop('recNet requires jmvcore to be installed (restart may be required)')

    if ( ! missing(y1)) y1 <- jmvcore::resolveQuo(jmvcore::enquo(y1))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(y1), y1, NULL))


    options <- recNetOptions$new(
        y1 = y1,
        standardise = standardise,
        emLag = emLag,
        emDim = emDim,
        Gweight = Gweight,
        Gdirect = Gdirect,
        Glabels = Glabels,
        Glayout = Glayout,
        PruneDegree = PruneDegree,
        PruneWeight = PruneWeight,
        nsize = nsize,
        fixRR = fixRR,
        fixRAD = fixRAD,
        fixed = fixed,
        DLmin = DLmin,
        DLmax = DLmax,
        VLmin = VLmin,
        VLmax = VLmax,
        HLmin = HLmin,
        HLmax = HLmax,
        theiler = theiler,
        norm = norm)

    analysis <- recNetClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
