
# This file is automatically generated, you probably don't want to edit this

ssgUNIOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ssgUNIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            y1 = NULL,
            time = NULL,
            v1_labels = "",
            v1_Nstates = 0,
            ssgUNIlag = 1,
            MinReturns = 2,
            MaxReturnTime = 0,
            MaxReturnVisits = 0,
            MinEventDuration = 0,
            MinCellDuration = 0, ...) {

            super$initialize(
                package='casnetjmv',
                name='ssgUNI',
                requiresData=TRUE,
                ...)

            private$..y1 <- jmvcore::OptionVariable$new(
                "y1",
                y1,
                rejectUnusedLevels=FALSE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..v1_labels <- jmvcore::OptionString$new(
                "v1_labels",
                v1_labels,
                default="")
            private$..v1_Nstates <- jmvcore::OptionInteger$new(
                "v1_Nstates",
                v1_Nstates,
                default=0)
            private$..ssgUNIlag <- jmvcore::OptionNumber$new(
                "ssgUNIlag",
                ssgUNIlag,
                default=1)
            private$..MinReturns <- jmvcore::OptionNumber$new(
                "MinReturns",
                MinReturns,
                default=2)
            private$..MaxReturnTime <- jmvcore::OptionNumber$new(
                "MaxReturnTime",
                MaxReturnTime,
                default=0)
            private$..MaxReturnVisits <- jmvcore::OptionNumber$new(
                "MaxReturnVisits",
                MaxReturnVisits,
                default=0)
            private$..MinEventDuration <- jmvcore::OptionNumber$new(
                "MinEventDuration",
                MinEventDuration,
                default=0)
            private$..MinCellDuration <- jmvcore::OptionNumber$new(
                "MinCellDuration",
                MinCellDuration,
                default=0)

            self$.addOption(private$..y1)
            self$.addOption(private$..time)
            self$.addOption(private$..v1_labels)
            self$.addOption(private$..v1_Nstates)
            self$.addOption(private$..ssgUNIlag)
            self$.addOption(private$..MinReturns)
            self$.addOption(private$..MaxReturnTime)
            self$.addOption(private$..MaxReturnVisits)
            self$.addOption(private$..MinEventDuration)
            self$.addOption(private$..MinCellDuration)
        }),
    active = list(
        y1 = function() private$..y1$value,
        time = function() private$..time$value,
        v1_labels = function() private$..v1_labels$value,
        v1_Nstates = function() private$..v1_Nstates$value,
        ssgUNIlag = function() private$..ssgUNIlag$value,
        MinReturns = function() private$..MinReturns$value,
        MaxReturnTime = function() private$..MaxReturnTime$value,
        MaxReturnVisits = function() private$..MaxReturnVisits$value,
        MinEventDuration = function() private$..MinEventDuration$value,
        MinCellDuration = function() private$..MinCellDuration$value),
    private = list(
        ..y1 = NA,
        ..time = NA,
        ..v1_labels = NA,
        ..v1_Nstates = NA,
        ..ssgUNIlag = NA,
        ..MinReturns = NA,
        ..MaxReturnTime = NA,
        ..MaxReturnVisits = NA,
        ..MinEventDuration = NA,
        ..MinCellDuration = NA)
)

ssgUNIResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        warnings = function() private$.items[["warnings"]],
        tblTS = function() private$.items[["tblTS"]],
        tsplot = function() private$.items[["tsplot"]],
        SSGplot = function() private$.items[["SSGplot"]],
        tblSSG = function() private$.items[["tblSSG"]],
        tblSSGstates = function() private$.items[["tblSSGstates"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Univariate State Space Grid")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warnings",
                title="Notes"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tblTS",
                title="Time series descriptives",
                rows=2,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="vlevel", 
                        `title`="type", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="integer", 
                        `title`="valid N"),
                    list(
                        `name`="na", 
                        `type`="integer", 
                        `title`="NA values"),
                    list(
                        `name`="uni_obs", 
                        `title`="# of unique observed states ", 
                        `type`="number"),
                    list(
                        `name`="uni_exp", 
                        `title`="# of unique expected states", 
                        `type`="number"),
                    list(
                        `name`="discretised", 
                        `title`="discretised?", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="tsplot",
                title="Nominal time series",
                width=700,
                height=300,
                renderFun=".tsplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="SSGplot",
                title="State Space Grid",
                width=700,
                height=500,
                renderFun=".SSGplot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tblSSG",
                title="Grid measures",
                rows=1,
                columns=list(
                    list(
                        `name`="Nstates", 
                        `title`="Unique states", 
                        `type`="number"),
                    list(
                        `name`="Ntraj", 
                        `title`="Unique trajectories", 
                        `type`="number"),
                    list(
                        `name`="Nreturns", 
                        `title`="N returns", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tblSSGstates",
                title="State measures",
                rows=0,
                columns=list(
                    list(
                        `name`="stateName", 
                        `title`="State"),
                    list(
                        `name`="Nvisits", 
                        `title`="# of Visits", 
                        `type`="number"),
                    list(
                        `name`="MNduration", 
                        `title`="Mean Visit duration", 
                        `type`="number"),
                    list(
                        `name`="SDduration", 
                        `title`="SD Visit duration", 
                        `type`="number"),
                    list(
                        `name`="Nevents", 
                        `title`="# of Events", 
                        `type`="number"),
                    list(
                        `name`="MNevent", 
                        `title`="Mean Event duration", 
                        `type`="number"),
                    list(
                        `name`="SDevent", 
                        `title`="SD Event duration", 
                        `type`="number"),
                    list(
                        `name`="MNreturn", 
                        `title`="Mean return time", 
                        `type`="number"),
                    list(
                        `name`="SDreturn", 
                        `title`="SD return time", 
                        `type`="number"))))}))

ssgUNIBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ssgUNIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'casnetjmv',
                name = 'ssgUNI',
                version = c(1,0,0),
                options = options,
                results = ssgUNIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Univariate State Space Grid
#'
#' 
#' @param data .
#' @param y1 An unordered categorical state variable
#' @param time A variable indicating time
#' @param v1_labels .
#' @param v1_Nstates .
#' @param ssgUNIlag .
#' @param MinReturns .
#' @param MaxReturnTime .
#' @param MaxReturnVisits .
#' @param MinEventDuration .
#' @param MinCellDuration .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$warnings} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tblTS} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tsplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$SSGplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tblSSG} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tblSSGstates} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tblTS$asDF}
#'
#' \code{as.data.frame(results$tblTS)}
#'
#' @export
ssgUNI <- function(
    data,
    y1 = NULL,
    time = NULL,
    v1_labels = "",
    v1_Nstates = 0,
    ssgUNIlag = 1,
    MinReturns = 2,
    MaxReturnTime = 0,
    MaxReturnVisits = 0,
    MinEventDuration = 0,
    MinCellDuration = 0) {

    if ( ! requireNamespace('jmvcore'))
        stop('ssgUNI requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(y1), y1, NULL),
            `if`( ! missing(time), time, NULL))

    options <- ssgUNIOptions$new(
        y1 = y1,
        time = time,
        v1_labels = v1_labels,
        v1_Nstates = v1_Nstates,
        ssgUNIlag = ssgUNIlag,
        MinReturns = MinReturns,
        MaxReturnTime = MaxReturnTime,
        MaxReturnVisits = MaxReturnVisits,
        MinEventDuration = MinEventDuration,
        MinCellDuration = MinCellDuration)

    results <- ssgUNIResults$new(
        options = options)

    analysis <- ssgUNIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
